// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Quote struct {
	ID     string `json:"id"`
	Quote  string `json:"quote"`
	Author string `json:"author"`
}

type QuoteInput struct {
	Quote  string `json:"quote"`
	Author string `json:"author"`
}

type Response struct {
	ID string `json:"id"`
}
